import assert from 'node:assert/strict'
import { createRequire } from 'node:module'
import test from 'node:test'
import { barcodeSvg } from './barcode'

const require = createRequire(import.meta.url)
const sharp = createRequire(require.resolve('next/package.json'))('sharp')
const { MultiFormatReader, BinaryBitmap, HybridBinarizer, RGBLuminanceSource } = createRequire(require.resolve('@zxing/browser/package.json'))('@zxing/library')

test('mobile decoder reads the actual Code 128 labels generated by the ERP', async () => {
  for (const code of ['RM-CORN', 'SEED-RM-01', '1234567890123']) {
    const { data, info } = await sharp(Buffer.from(barcodeSvg(code, { height: 96, module: 3 }))).flatten({ background: '#ffffff' }).removeAlpha().raw().toBuffer({ resolveWithObject: true })
    const pixels = new Int32Array(info.width * info.height)
    for (let i = 0; i < pixels.length; i++) pixels[i] = (data[i * 3] << 16) | (data[i * 3 + 1] << 8) | data[i * 3 + 2]
    const bitmap = new BinaryBitmap(new HybridBinarizer(new RGBLuminanceSource(pixels, info.width, info.height)))
    assert.equal(new MultiFormatReader().decode(bitmap).getText(), code)
  }
})
