export const PERMISSIONS = [
  'users.read',
  'users.manage',
  'roles.read',
  'roles.manage',
  'settings.read',
  'settings.update',
  'warehouses.read',
  'warehouses.manage',
  'inventory.read',
  'inventory.transfer.create',
  'inventory.adjust',
  'inventory.ledger.read',
  'purchasing.read',
  'purchasing.po.create',
  'purchasing.po.approve',
  'purchasing.gr.create',
  'production.read',
  'production.create',
  'production.complete',
  'production.cost.approve',
  'production.cost.recalculate',
  'production.variance.thresholds',
  'qc.read',
  'qc.manage',
  'qc.release',
  'qc.limits',
  'sales.read',
  'sales.create',
  'sales.confirm',
  'sales.payments.manage',
  'accounting.read',
  'accounting.manage',
  'tax.read',
  'tax.manage',
  'expenses.manage',
  'expenses.approve',
  'employees.read',
  'employees.manage',
  'attendance.read',
  'attendance.manage',
  'payroll.manage',
  'payroll.approve',
  'payroll.pay',
  'approvals.decide',
  'barcode.scan',
  'reports.read',
  'audit.read',
  'notifications.read',
  'fleet.read',
  'fleet.manage',
  'fleet.service.manage',
  'obligations.read',
  'obligations.manage',
  'obligations.pay',
  'documents.read',
  'documents.manage',
  'spareparts.read',
  'spareparts.manage',
  'packaging.read',
  'packaging.manage',
  'suppliers.communicate',
  'suppliers.approve',
  'scale.read',
  'scale.manage',
  'distribution.read',
  'distribution.manage',
  'delivery.track',
  'utilities.read',
  'utilities.manage',
  'maintenance.read',
  'maintenance.manage',
  'bank.read',
  'bank.manage',
  'recipes.custom',
  'pricing.custom',
] as const

export type Permission = (typeof PERMISSIONS)[number]

export const ROLE_LABELS = {
  GM: 'المدير العام',
  ACCOUNTANT: 'المحاسب والموارد البشرية',
  OPERATIONS: 'المستودع والإنتاج والمبيعات',
  QUALITY: 'مسؤول الجودة',
  DRIVER: 'سائق',
  STOREKEEPER: 'أمين المخزن',
  PRODUCTION: 'مسؤول الإنتاج',
  MAINTENANCE: 'مسؤول الصيانة',
  SALES: 'مسؤول المبيعات',
} as const

export type RoleKey = keyof typeof ROLE_LABELS

const ALL = [...PERMISSIONS]

export const DEFAULT_ROLE_PERMISSIONS: Record<RoleKey, Permission[]> = {
  GM: ALL,
  ACCOUNTANT: [
    'users.read',
    'settings.read',
    'purchasing.read',
    'sales.read',
    'sales.payments.manage',
    'accounting.read',
    'accounting.manage',
    'tax.read',
    'tax.manage',
    'expenses.manage',
    'employees.read',
    'employees.manage',
    'attendance.read',
    'attendance.manage',
    'payroll.manage',
    'payroll.pay',
    'reports.read',
    'audit.read',
    'notifications.read',
    'qc.read',
    'production.cost.approve',
    'fleet.read',
    'obligations.read',
    'obligations.pay',
    'documents.read',
  ],
  OPERATIONS: [
    'warehouses.read',
    'inventory.read',
    'inventory.transfer.create',
    'inventory.adjust',
    'inventory.ledger.read',
    'purchasing.read',
    'purchasing.po.create',
    'purchasing.gr.create',
    'production.read',
    'production.create',
    'production.complete',
    'qc.read',
    'qc.manage',
    'sales.read',
    'sales.create',
    'sales.confirm',
    'barcode.scan',
    'reports.read',
    'notifications.read',
    'fleet.read',
    'fleet.manage',
    'fleet.service.manage',
    'documents.read',
  ],
  QUALITY: ['qc.read', 'qc.manage', 'inventory.read', 'production.read', 'reports.read', 'notifications.read'],
  DRIVER: ['fleet.read', 'reports.read', 'notifications.read'],
  STOREKEEPER: [
    'warehouses.read',
    'inventory.read',
    'inventory.transfer.create',
    'inventory.adjust',
    'inventory.ledger.read',
    'purchasing.read',
    'purchasing.gr.create',
    'barcode.scan',
    'packaging.read',
    'spareparts.read',
    'reports.read',
    'notifications.read',
  ],
  PRODUCTION: [
    'inventory.read',
    'warehouses.read',
    'production.read',
    'production.create',
    'production.complete',
    'qc.read',
    'qc.manage',
    'packaging.read',
    'packaging.manage',
    'scale.read',
    'scale.manage',
    'reports.read',
    'notifications.read',
  ],
  MAINTENANCE: [
    'maintenance.read',
    'maintenance.manage',
    'spareparts.read',
    'spareparts.manage',
    'inventory.read',
    'warehouses.read',
    'inventory.ledger.read',
    'purchasing.read',
    'fleet.service.manage',
    'reports.read',
    'notifications.read',
  ],
  SALES: [
    'sales.read',
    'sales.create',
    'sales.confirm',
    'distribution.read',
    'distribution.manage',
    'delivery.track',
    'pricing.custom',
    'reports.read',
    'notifications.read',
  ],
}

export function hasPermission(permissions: readonly string[], required: string) {
  return permissions.includes(required)
}

/** Bump when built-in roles gain new default permissions. The migration adds only these keys. */
export const PERMISSIONS_VERSION = 8

export const PERMISSIONS_INTRODUCED: Record<number, Partial<Record<RoleKey, Permission[]>>> = {
  1: {
    GM: ['qc.read', 'qc.manage', 'qc.release', 'qc.limits'],
    ACCOUNTANT: ['qc.read'],
    OPERATIONS: ['qc.read', 'qc.manage'],
  },
  2: {
    QUALITY: ['qc.read', 'qc.manage', 'inventory.read', 'production.read', 'reports.read', 'notifications.read'],
  },
  3: {
    GM: ['production.cost.approve'],
    ACCOUNTANT: ['production.cost.approve'],
  },
  4: {
    GM: ['fleet.read', 'fleet.manage', 'obligations.read', 'obligations.manage', 'obligations.pay', 'documents.read', 'documents.manage'],
    ACCOUNTANT: ['fleet.read', 'obligations.read', 'obligations.pay', 'documents.read'],
    OPERATIONS: ['fleet.read', 'fleet.manage', 'documents.read'],
    DRIVER: ['fleet.read', 'reports.read', 'notifications.read'],
  },
  5: {
    GM: ['spareparts.read', 'spareparts.manage', 'packaging.read', 'packaging.manage', 'suppliers.communicate', 'suppliers.approve', 'scale.read', 'scale.manage', 'distribution.read', 'distribution.manage', 'delivery.track', 'utilities.read', 'utilities.manage', 'maintenance.read', 'maintenance.manage', 'bank.read', 'bank.manage', 'recipes.custom', 'pricing.custom'],
    ACCOUNTANT: ['spareparts.read', 'packaging.read', 'suppliers.communicate', 'suppliers.approve', 'distribution.read', 'utilities.read', 'bank.read', 'bank.manage', 'pricing.custom'],
    OPERATIONS: ['spareparts.read', 'spareparts.manage', 'packaging.read', 'packaging.manage', 'scale.read', 'scale.manage', 'distribution.read', 'distribution.manage', 'delivery.track', 'maintenance.read', 'maintenance.manage'],
  },
  6: {
    // Month-close cost recalculation is a GM-only control.
    GM: ['production.cost.recalculate'],
  },
  7: {
    // Per-product / per-recipe variance thresholds are a GM-only control.
    GM: ['production.variance.thresholds'],
  },
  8: {
    GM: ['fleet.service.manage'],
    OPERATIONS: ['fleet.service.manage'],
    STOREKEEPER: [...DEFAULT_ROLE_PERMISSIONS.STOREKEEPER],
    PRODUCTION: [...DEFAULT_ROLE_PERMISSIONS.PRODUCTION],
    MAINTENANCE: [...DEFAULT_ROLE_PERMISSIONS.MAINTENANCE],
    SALES: [...DEFAULT_ROLE_PERMISSIONS.SALES],
  },
}
